version: '3.5'
services:
  postgres:
    build: ./postgres
    ports:
      - "5455:5432"
    volumes:
      - "./postgres/data:/root/data"
    tty: true
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      default:
        ipv4_address: 172.16.238.10
  backend_php:
    build: ./backend
    ports:
      - "9015:9015"
    volumes:
      - "./backend/src:/var/www/html"
      - "~/.ssh:/root/.ssh"
    tty: true
    networks:
      default:
        ipv4_address: 172.16.238.2
networks:
  default:
    name: postgres_docker_proxy_runner
    ipam:
      config:
        - subnet: 172.16.238.0/24